### ISSUE TITLE
Alignment issue in song Anonymous__lanative__lanative

### ISSUE THREAD

**Issue by sainttail** [CPJKU/msmd#5]
I run the tutorial on that song and using
```python
ordered_note_mungos = score.get_ordered_notes(filter_tied=False, reverse_columns=False, return_columns=True)
```
to get order note, as you can see in the screenshot below the alignment of note `83` and `86` is wrong. The left-right hand should not play together like the alignment done. (The note should be separate like note `71` and `72`

![Untitled](https://user-images.githubusercontent.com/3015139/57460478-5dc3f280-729f-11e9-8625-79938bf87f97.png)

**Comment by stefan-balke** [comment]
Hi sainttail,

I just double-checked the alignments and for me it looks okay. See attached the two screenshots I made by using the `msmd_manager_app.py`:

![Screenshot from 2019-05-10 13-15-53](https://user-images.githubusercontent.com/7326732/57523729-09178a80-7326-11e9-9556-5c744f7e4b41.png)
![Screenshot from 2019-05-10 13-16-01](https://user-images.githubusercontent.com/7326732/57523731-0ae14e00-7326-11e9-8e50-d3b005694835.png)

It would help if you provide us with a small running code example which we then test here to reproduce the error.

Thanks!
Stefan

**Comment by sainttail** [comment]
@stefan-balke Thanks for your attention. This is the `.ipynb` file that I ran and the zip for the msmd file that I have downloaded for that song.

[Anonymous__lanative__lanative.zip](https://github.com/CPJKU/msmd/files/3166684/Anonymous__lanative__lanative.zip)

[Loading Piece Data.zip](https://github.com/CPJKU/msmd/files/3166688/Loading.Piece.Data.zip)

And this is the pip library that I use

<details>
<pre>
Abjad==3.0.0
alabaster==0.7.12
Babel==2.6.0
backcall==0.1.0
bleach==3.0.2
certifi==2018.11.29
chardet==3.0.4
cloudpickle==0.6.1
colorama==0.4.1
cycler==0.10.0
Cython==0.29.2
dask==1.0.0
decorator==4.3.0
defusedxml==0.5.0
docutils==0.14
dtw==1.3
entrypoints==0.2.3
idna==2.8
imagesize==1.1.0
ipykernel==5.1.0
ipython==7.2.0
ipython-genutils==0.2.0
ipywidgets==7.4.2
jedi==0.13.2
Jinja2==2.10
jsonschema==2.6.0
jupyter==1.0.0
jupyter-client==5.2.4
jupyter-console==6.0.0
jupyter-core==4.4.0
kiwisolver==1.0.1
lxml==4.2.5
madmom==0.16.1
MarkupSafe==1.1.0
matplotlib==3.0.2
midi==0.2.3
mido==1.2.9
mistune==0.8.4
muscima==0.10.0
music21==5.5.0
nbconvert==5.4.0
nbformat==4.4.0
networkx==2.2
notebook==5.7.4
numpy==1.15.4
opencv-python==3.4.4.19
packaging==18.0
pandocfilters==1.4.2
parso==0.3.1
pickleshare==0.7.5
Pillow==5.3.0
ply==3.11
prometheus-client==0.5.0
prompt-toolkit==2.0.7
Pygments==2.3.1
pyparsing==2.3.0
python-dateutil==2.7.5
pytz==2018.7
PyWavelets==1.0.1
pywinpty==0.5.5
PyYAML==3.13
pyzmq==17.1.2
qtconsole==4.4.3
requests==2.21.0
roman==3.1
scikit-image==0.14.1
scikit-learn==0.20.2
scipy==1.2.0
Send2Trash==1.5.0
six==1.12.0
snowballstemmer==1.2.1
Sphinx==1.8.2
sphinx-autodoc-typehints==1.6.0
sphinx-rtd-theme==0.4.2
sphinxcontrib-websupport==1.1.0
terminado==0.8.1
testpath==0.4.2
toolz==0.9.0
tornado==5.1.1
tqdm==4.28.1
traitlets==4.3.2
Unidecode==1.0.23
uqbar==0.2.15
urllib3==1.24.1
virtualenv==16.1.0
wcwidth==0.1.7
webencodings==0.5.1
widgetsnbextension==3.4.2
</pre>
</details>

Thanks.

**Comment by stefan-balke** [comment]
Thanks, I'm going to give it a look but am traveling this week!

**Comment by stefan-balke** [comment]
Hey @sainttail,

sorry for the delay. I just pushed v1.1 (https://github.com/CPJKU/msmd/tree/v1.1)
Can you try it with this version again?

Best
Stefan

**Comment by sainttail** [comment]
I pull the latest version v1.1 .Still didn't solve this however, the image look less sharp than before

![test](https://user-images.githubusercontent.com/3015139/60673890-0b6c1000-9ea3-11e9-9461-794088408d85.png)

PS. I use window is there a problem?

**Comment by dmatte** [comment]
Hi,

as @stefan-balke checked the piece with the app and it seemed to be fine
it might be that only some of notes in this piece are not aligned correctly.

As the sheet music and MIDIs in the datasete are aligned automatically (using DTW)
there are cases where this automatic alignment is not 100% correct
(e.g. some notes might be off).
Could this be the case here?

Best, Matthias
